#ifndef LUIGI_H
#define LUIGI_H
/*
 * apps/luigi.h — Luigi AI Sohbet Penceresi
 * ============================================
 * Matematik + Dil Algilama + Bilgi Tabani'ni birlestiren
 * sohbet arayuzu. Mesaj gecmisi, kaydirma, kilavuz uretici.
 */
#include "../gui.h"
#include "../kernel/vfs.h"
#include "../kernel/vfs_persist.h"
#include "luigi_math.h"
#include "luigi_kb.h"

struct LuigiMsg {
    char text[180];
    bool from_user;
};

struct LuigiAI : public Window {
    static const int MSG_MAX = 24;
    LuigiMsg history[MSG_MAX];
    int   msg_count;
    int   scroll;

    char  input_buf[120];
    int   input_len;
    int   input_cursor;

    LuigiLang last_lang;

    LuigiAI():Window("Luigi AI",140,60,380,360){
        msg_count=0; scroll=0;
        input_buf[0]=0; input_len=0; input_cursor=0;
        last_lang=LUIGI_TR;
        push_msg(false,
            "Merhaba! Ben Luigi. Matematik sorabilir, LightOS hakkinda soru sorabilir, ya da sohbet edebiliriz. / Hi! I'm Luigi. Ask me math, LightOS questions, or just chat.");
    }

    void push_msg(bool from_user, const char* text){
        if(msg_count>=MSG_MAX){
            for(int i=0;i<MSG_MAX-1;i++) history[i]=history[i+1];
            msg_count=MSG_MAX-1;
        }
        int i=0; while(text[i]&&i<179){ history[msg_count].text[i]=text[i]; i++; }
        history[msg_count].text[i]=0;
        history[msg_count].from_user=from_user;
        msg_count++;
        scroll=0; /* en alta git */
    }

    /* ── Ana yanit üretici: matematik mi, KB mi, fallback mi ── */
    void generate_response(const char* msg){
        luigi_rng_feed(msg);

        LuigiLang lang = luigi_detect_lang(msg, last_lang);
        last_lang = lang;

        char resp[200];

        /* Kilavuz tetikleyici */
        if(luigi_substr_ci(msg,"kilavuz olustur") || luigi_substr_ci(msg,"rehber olustur") ||
           luigi_substr_ci(msg,"create guide") || luigi_substr_ci(msg,"make guide")){
            write_guide();
            if(lang==LUIGI_TR) push_msg(false,"Kilavuzu olusturdum! Dosyalar'dan Guide.txt'i acabilirsin.");
            else push_msg(false,"Guide created! You can open Guide.txt from File Manager.");
            return;
        }

        /* Matematik mi? */
        if(luigi_looks_like_math(msg)){
            LuigiMathResult r = luigi_eval_math(msg);
            if(r.ok){
                char numbuf[32];
                lm_dtoa(r.value, numbuf, 6);
                int oi=0;
                const char* lead = (lang==LUIGI_TR) ? "Sonuc: " : "Result: ";
                while(*lead) resp[oi++]=*lead++;
                int ni=0; while(numbuf[ni]) resp[oi++]=numbuf[ni++];
                resp[oi]=0;
                push_msg(false,resp);
            } else {
                int oi=0;
                const char* lead = (lang==LUIGI_TR) ? "Hesaplama hatasi: " : "Math error: ";
                while(*lead) resp[oi++]=*lead++;
                int ei=0; while(r.error[ei]&&oi<190) resp[oi++]=r.error[ei++];
                resp[oi]=0;
                push_msg(false,resp);
            }
            return;
        }

        /* Bilgi tabani */
        int topic = luigi_match_topic(msg, lang);
        if(topic>=0){
            luigi_build_kb_response(topic, lang, resp, 200);
            push_msg(false, resp);
            return;
        }

        /* Fallback */
        if(lang==LUIGI_TR)
            push_msg(false,"Bunu tam anlayamadim. Matematik sorabilir, ya da LightOS uygulamalari/kisayollari hakkinda sorabilirsin. 'Ne yapabilirsin?' diye sorabilirsin.");
        else
            push_msg(false,"I didn't quite catch that. Try asking me math, or ask about LightOS apps/shortcuts. You can also ask 'what can you do?'");
    }

    void write_guide(){
        char buf[3500]; int p=0;
        auto ap=[&](const char* s){ while(*s && p<3490) buf[p++]=*s++; };
        ap("LightOS 2 Pro - Usage Guide\n");
        ap("(Generated by Luigi AI)\n");
        ap("================================\n\n");
        ap("APPLICATIONS\n--------------------------------\n");
        ap("Notepad        - text editor, Ctrl+S to save\n");
        ap("Calculator     - basic arithmetic\n");
        ap("File Manager   - browse the VFS, double-click folders\n");
        ap("Settings       - keyboard / theme / wallpaper\n");
        ap("Terminal       - ls cd cat echo mkdir rm pwd clear ver mem help\n");
        ap("Paint          - pixel art, Pen/Eraser/Fill/Line\n");
        ap("Clock          - analog + digital RTC clock\n");
        ap("System Info    - RAM, resolution, VFS, dev mode status\n");
        ap("LightSurf      - browser, about: and file:// pages\n");
        ap("Calendar       - monthly view, notes saved to VFS\n");
        ap("Task Manager   - window list, End Task, RAM bar\n");
        ap("XaefGAMES      - folder with Snake, Tetris, Pong, Minesweeper\n\n");
        ap("SHORTCUTS\n--------------------------------\n");
        ap("Ctrl+S   Save file (Notepad)\n");
        ap("Ctrl+F   Search in page (LightSurf)\n");
        ap("Ctrl+D   Bookmark page (LightSurf)\n");
        ap("R        Rename item (File Manager)\n");
        ap("F4 x5    Activate Developer Mode (at boot)\n\n");
        ap("DEVELOPER MODE\n--------------------------------\n");
        ap("Press F4 five times during boot animation, then Y to confirm.\n");
        ap("Unlocks 10 dev tools: Mem Viewer, Port I/O, VFS Inspector,\n");
        ap("CPU Registers, IRQ Monitor, Stack View, Kernel Log,\n");
        ap("BSOD Tester, RTC Inspector, Panic Simulator.\n\n");
        ap("NETWORK\n--------------------------------\n");
        ap("Supports RTL8139 and Intel e1000 NICs.\n");
        ap("QEMU: -device e1000,netdev=n0 -netdev user,id=n0\n\n");
        ap("GAMES\n--------------------------------\n");
        ap("Snake:       WASD/arrows, SPACE start, R restart\n");
        ap("Tetris:      A/D move, S drop, W rotate, SPACE start\n");
        ap("Pong:        W/S move paddle, SPACE start\n");
        ap("Minesweeper: click cells, click face to restart\n\n");
        ap("--------------------------------\n");
        ap("LightOS 2 Pro - by Xaef BTL, 2026\n");
        buf[p]=0;

        int node = g_vfs.FindChild(0,"Guide.txt");
        if(node>=0) g_vfs.WriteFile(node, buf);
        else g_vfs.MkFile(0, "Guide.txt", buf);
        if(g_disk.present) vfs_save(); /* Explorer'dan hemen doğru içerikle açılabilsin */
    }

    /* ── Metin sarma: text'i max_chars genislikte satirlara bol ── */
    int wrap_text(const char* text, int max_chars, char lines[][64], int max_lines){
        int lc=0; int ti=0; int len=0; while(text[len])len++;
        while(ti<len && lc<max_lines){
            int line_start=ti, last_space=-1, cur=0;
            while(ti<len && cur<max_chars && text[ti]!='\n'){
                if(text[ti]==' ') last_space=ti;
                ti++; cur++;
            }
            int line_end;
            if(ti<len && text[ti]=='\n'){ line_end=ti; ti++; }
            else if(ti>=len) line_end=ti;
            else if(last_space>line_start){ line_end=last_space; ti=last_space+1; }
            else line_end=ti;
            int ll=line_end-line_start; if(ll>62)ll=62;
            for(int i=0;i<ll;i++) lines[lc][i]=text[line_start+i];
            lines[lc][ll]=0;
            lc++;
        }
        return lc;
    }

    void DrawContent() override {
        int ox=x+2, oy=y+26;
        int chat_h = h-28-34; /* alt input bar için yer */
        DrawRect(ox,oy,w-4,chat_h,LerpColor(TP().win_content,0x000000,8,100));

        /* Mesajlari satirlara bol ve toplam yukseklik hesapla (alttan basla) */
        char wrapped[8][64];
        int max_chars=(w-60)/9; if(max_chars>62)max_chars=62; if(max_chars<10)max_chars=10;

        /* Once tum mesajlarin toplam satir sayisini ve yuksekligini hesapla */
        int line_h=14, bubble_gap=6;
        int total_h=0;
        int msg_line_counts[MSG_MAX];
        for(int m=0;m<msg_count;m++){
            int lc=wrap_text(history[m].text,max_chars,wrapped,8);
            msg_line_counts[m]=lc;
            total_h += lc*line_h + bubble_gap + 6;
        }

        int avail_h=chat_h-8;
        int start_y;
        if(total_h<=avail_h){ start_y=oy+avail_h-total_h+4; }
        else { start_y=oy+4-(total_h-avail_h)+scroll; }

        int draw_y=start_y;
        for(int m=0;m<msg_count;m++){
            int lc=wrap_text(history[m].text,max_chars,wrapped,8);
            int bub_h=lc*line_h+8;
            bool usr=history[m].from_user;
            int bub_w=0;
            for(int i=0;i<lc;i++){ int sw2=StringWidth(wrapped[i]); if(sw2>bub_w)bub_w=sw2; }
            bub_w+=16; if(bub_w>w-50) bub_w=w-50;

            int bx = usr ? (ox+w-12-bub_w-8) : (ox+8);
            if(draw_y+bub_h>oy && draw_y<oy+chat_h){
                uint32_t bcol = usr ? LerpColor(WP_FrameFoc(),0x000000,10,100)
                                     : LerpColor(TP().win_content,0xFFFFFF,12,100);
                uint32_t tcol = usr ? 0xFFFFFF : 0x101010;
                DrawRect(bx,draw_y,bub_w,bub_h,bcol);
                DrawRectBorder(bx,draw_y,bub_w,bub_h,LerpColor(bcol,0xFFFFFF,25,100));
                for(int i=0;i<lc;i++)
                    DrawString(bx+8,draw_y+4+i*line_h,wrapped[i],tcol);
            }
            draw_y+=bub_h+bubble_gap;
        }

        /* Üst gradient fade (eski mesajlar varsa) */
        if(total_h>avail_h)
            DrawGradientV(ox,oy,w-4,10,LerpColor(TP().win_content,0x000000,8,100),
                          DimColor(LerpColor(TP().win_content,0x000000,8,100),0));

        /* ── Input bar ── */
        int iy=oy+chat_h+4;
        DrawRect(ox,iy,w-4,1,0xC0BCB4);
        DrawRect(ox+4,iy+4,w-50,24,0xFFFFFF);
        DrawRectBorder(ox+4,iy+4,w-50,24,WP_FrameFoc());
        DrawString(ox+10,iy+10,input_buf,0x202020);
        int cp2=ox+10+input_cursor*9;
        /* basit blink yok ama cursor cizgisi */
        DrawRect(cp2,iy+6,2,18,WP_FrameFoc());

        DrawGradientV(ox+w-40,iy+4,32,24,WP_TitleTop(true),WP_TitleBot(true));
        DrawBevel(ox+w-40,iy+4,32,24,true);
        DrawString(ox+w-34,iy+10,">",WP_TitleText(true));
    }

    void OnClickContent(int mx,int my) override {
        int oy=y+26, chat_h=h-28-34;
        int iy=oy+chat_h+4;
        /* Input bar */
        if(my>=iy+4&&my<=iy+28&&mx>=x+6&&mx<=x+w-46){
            /* cursoru tikladigi yere yakin konuma getir (basit) */
            input_cursor=input_len;
            return;
        }
        /* Send butonu */
        if(my>=iy+4&&my<=iy+28&&mx>=x+w-38){
            send_current();
            return;
        }
    }

    void send_current(){
        if(input_len==0) return;
        push_msg(true, input_buf);
        char tmp[120]; int i=0; while(input_buf[i]){tmp[i]=input_buf[i];i++;} tmp[i]=0;
        input_buf[0]=0; input_len=0; input_cursor=0;
        generate_response(tmp);
    }

    void KeyPress(unsigned int cp){
        if(cp=='\n'||cp=='\r'){ send_current(); return; }
        if(cp=='\b'){
            if(input_cursor>0){
                for(int i=input_cursor-1;i<input_len;i++) input_buf[i]=input_buf[i+1];
                input_cursor--; input_len--;
            }
            return;
        }
        if(cp==0xFF01){ if(scroll<2000) scroll+=14; return; } /* up = scroll older */
        if(cp==0xFF02){ if(scroll>0) scroll-=14; return; }    /* down = scroll newer */
        if(cp>=' ' && cp<127 && input_len<118){
            for(int i=input_len;i>=input_cursor;i--) input_buf[i+1]=input_buf[i];
            input_buf[input_cursor]=(char)cp;
            input_cursor++; input_len++;
            input_buf[input_len]=0;
        }
    }
};
#endif
